### ISSUE TITLE
Hardware: Update the boards to the new PCB standard

### ISSUE THREAD

**Issue by andrempmattos** [spacelab-ufsc/interface-board#39]

**Comment by YanAzer** [comment]
The repository didn't follow perfectly the (PCB standard rules)[] since it was a hardware project of 3 boards, but many changes were done to improve the overall source files names, directory organization and output. The changes were done with many commits, just to name a few 236cfc2598377997e421c57118ccf303d5609164, 478ef096d5f2498a74f3d4c07593be2dd4aa01b6, 6cdae57a20f86435ae860cb2187526eccee5501d, 7e1c9b9f878a1c758af2270bdad553cf3c6d72dc (the last).
